# This is a config for E2B sandbox template.
# You can use template ID (nn30pxpz2jmyn4xurrpp) or template name (vibe-nextjs-armin-123-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-armin-123-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-armin-123-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-armin-123-2')

team_id = "5e896811-2d90-4f17-af7b-b0de6ccf395e"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-armin-123-2"
template_id = "nn30pxpz2jmyn4xurrpp"
